### PR TITLE
Patch e3078ae

### PR DESCRIPTION
**Pull request by madbosun**

### CODE REVIEW

**Comment by slepton** [comment]
In case you are bored any idea how to fix this linking error?

/usr/lib64/libpsm_infinipath.so.1: undefined reference to `knem_put'

**Comment by madbosun** [comment]
Where does this show up? and what are we linking?

slepton wrote:

**Comment by nakul02** [comment]
Could you also mention
1. Cmake or autoconf 
2. Compiler & version. 
3. Compiler flags if any

**Comment by slepton** [comment]
This was just suppose to be a message to Jason. You can ignore this.

**Pull request closed without merging**
